import Head from 'next/head'
import Image from 'next/image'
import { Banner } from '../components/Banner/Banner'
import BannerNav from '../components/BannerNav/BannerNav'
import { Content } from '../components/Content/Content'
import { Footer } from '../components/Footer/Footer'
import { NavBar } from '../components/NavBar/NavBar'
import TableContent from '../components/TableContent/TableContent'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Travel App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar></NavBar>
      <BannerNav></BannerNav>
      <Banner></Banner>
      <TableContent></TableContent>
      <Content></Content>
      <Footer></Footer>
      

      
    </div>
  )
}
